### ISSUE TITLE
Separate zToken from ZeroCollateral

### ISSUE THREAD

**Issue by haythem96** [Zero-Collateral/zero-collateral-v1#16]
The current implementation make it harder to scale the protocol (integrating other underlying asset).

I propose the current architecture:
 - zToken contract : ERC20 token that represent the lender accumulated interest. (different underlying asset use different decimals, so will be great to calculate the decimals for the zToken in a dynamic way).
 - ZeroCollateralMain: create new zToken at the time of deployment + manage core functions (mint/deposit liquidity, redeem, liquidate...etc).
 - ZeroCollateralMain: a factory contract that can be owned by a DAO to govern the decision around what underlying asset to support (can be added at a later stage).

**Comment by alicevhenshaw** [comment]
Closing this issue as this separation happened.
